<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <include filename="$(find pr2_defs)/defs/head/head_sensor_package_gazebo.xacro" />
  <include filename="$(find pr2_defs)/defs/head/head_sensor_package_transmission.xacro" />

  <property name="stereo_size_x" value="0.005" />
  <property name="stereo_size_y" value="0.010" />
  <property name="stereo_size_z" value="0.005" />
  <property name="stereo_center_box_center_offset_x" value="0.00" />
  <property name="stereo_center_box_center_offset_z" value="0.05" />
  <property name="stereo_dx" value="0.00" />
  <property name="stereo_dy" value="-0.09" /> <!-- +y to the left -->
  <property name="stereo_dz" value="0.00" />
  <property name="stereo_rx" value="0.00" />
  <property name="stereo_ry" value="0.00" />
  <property name="stereo_rz" value="0.00" />

  <macro name="pr2_tilting_laser" params="name parent *origin">

    <joint name="${name}_mount_joint" type="revolute">
      <axis xyz="0 1 0" />
      <limit lower="-0.785" upper="1.57" effort="0.5292" velocity="100" />
      <safety_controller k_position="100" k_velocity="0.05" soft_lower_limit="${-0.785+0.0}" soft_upper_limit="${1.57-0.0}" />
      <calibration reference_position="-0.35" />
      <dynamics damping="0.008" />
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_mount_link"/>
    </joint>
    <link name="${name}_mount_link">

      <inertial>
        <mass value="0.05" />
        <origin xyz="-0.03 0 -0.03" rpy="0 0 0" />
        <inertia ixx="0.0001" ixy="0" ixz="0" 
                 iyy="0.00001" iyz="0" 
                 izz="0.0001" />
      </inertial>

      <visual name="${name}_mount_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_mount_visual_geom">
          <mesh filename="package://pr2_defs/meshes/hok_tilt.stl" />
        </geometry>
        
        <material name="Red" />
      </visual>

      <collision name="${name}_mount_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_mount_collision_geom" >
          <box size=".001 .001 .001" />
        </geometry>
      </collision>
    </link>

    <joint name="${name}_joint" type="fixed">
      <axis xyz="0 1 0" />
      <origin xyz="0 0 0.03" rpy="0 0 0" />
      <parent link="${name}_mount_link"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link" type="laser">

      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_visual_geom">
          <box size="0.001 0.001 0.001" />
        </geometry>
        
        <material name="Red" />
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_collision_geom" >
          <box size=".001 .001 .001" />
        </geometry>
      </collision>

    </link>

    <!-- extensions -->
    <pr2_tilting_laser_gazebo name="${name}"/>
    <pr2_tilting_laser_transmission name="${name}"/>
  </macro>



  <!-- Made by Kevin for A2 sensor package -->
  <!-- Origin is center mount screw on sensor plate mount -->
  <!-- When mounted properly, should have same origin as head plate frame -->
  <macro name="pr2_head_sensor_package" params="name hd_name stereo_name parent *origin">
    <joint name="${name}_frame_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link" >

      <inertial>
        <!-- Needs verification with CAD -->
        <mass value="0.05" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" izz="0.01" />
      </inertial>

      <!-- Should probably get real visuals here at some point -->
      <visual name="${name}_sensor_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_sensor_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
        
        <material name="Blue" />
      </visual>

      <collision name="${name}_sensor_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_sensor_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>

    <!-- Prosilica Camera -->
    <prosilica_cam name="${hd_name}" parent="${name}_link" >
      <!-- Center of camera is 109mm right of center screw, 35mm up -->
      <!-- Camera is slightly recessed from front, where is camera origin? Lens? -->
      <origin xyz="0 -0.109 0.035" rpy="0 0 0" />        
    </prosilica_cam>

    <!-- Stereocam -->
    <double_stereo_camera name="${stereo_name}" parent="${name}_link" >
      <origin xyz="0.0 0.0 0.003" rpy="0 0 0" />
    </double_stereo_camera>

    <!-- extensions -->
    <pr2_head_sensor_package_gazebo name="${name}" />

  </macro>

  <!-- Made by Kevin for double stereo camera for PR-2 Beta. -->
  <!-- Needs calibration verification, and CAD check. -->
  <macro name="double_stereo_camera" params="name parent *origin">
    <!-- Define link to stereo cameras, set origin relative to that -->
    <joint name="${name}_frame_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">

      <inertial>
        <!-- Needs verification with CAD -->
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" izz="0.01" />
      </inertial>

      <!-- Should probably get real visuals here at some point -->
      <visual name="${name}_double_stereo_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_double_stereo_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
        
        <material name="Blue" />
      </visual>

      <collision name="${name}_double_stereo_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_double_stereo_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>

    <!-- Wide camera is on robot right (hca1), narrow on left (hca2)? -->
    <!-- 15mm offset from center needs check with CAD -->
    <stereo_camera parent="${name}_link" name="wide_stereo" >
      <origin xyz="0 -0.015 0" rpy="0 0 0" />
    </stereo_camera>

    <stereo_camera parent="${name}_link" name="narrow_stereo" >
      <origin xyz="0 0.015 0" rpy="0 0 0" />
    </stereo_camera>

    <!-- extensions -->
    <double_stereo_camera_gazebo name="${name}" />
    
    <!-- extensions -->
    <stereo_camera_gazebo_wide name="wide_stereo" />
    <stereo_camera_gazebo_narrow name="narrow_stereo" />

  </macro>

  <macro name="stereo_camera" params="name parent *origin">
    
    <joint name="${name}_frame_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="${stereo_center_box_center_offset_x} 0 ${stereo_center_box_center_offset_z}" rpy="0 0 0" />
        <geometry name="${name}_visual_geom">
          <box size="${stereo_size_x} ${stereo_size_y} ${stereo_size_z}" />
        </geometry>
        
        <material name="Blue" />
      </visual>

      <collision name="${name}_collision">
        <origin xyz="${stereo_center_box_center_offset_x} 0 ${stereo_center_box_center_offset_z}" rpy="0 0 0" />
        <geometry name="${name}_collision_geom">
          <box size="${stereo_size_x} ${stereo_size_y} ${stereo_size_z}" />
        </geometry>
      </collision>
      
    </link>

    <joint name="${name}_optical_frame_joint" type="fixed">
      <origin xyz="${cal_stereo_x}            ${0.045+cal_stereo_y}   ${.0305+cal_stereo_z}" rpy="${-M_PI/2+cal_stereo_roll} ${0.0+cal_stereo_pitch} ${-M_PI/2+cal_stereo_yaw}" />
      <parent link="${name}_link"/>
      <child link="${name}_optical_frame"/>
    </joint>
    <link name="${name}_optical_frame" type="camera">

      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001"  ixy="0.0"  ixz="0.0"
                 iyy="0.001"  iyz="0.0"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_optical_frame_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_optical_frame_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
        
        <material name="Blue" />
      </visual>

      <collision name="${name}_optical_frame_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_optical_frame_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>

    </link>

    <joint name="${name}_l_stereo_camera_frame_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 ${-M_PI/2} ${M_PI/2}" />
      <parent link="${name}_optical_frame"/>
      <child link="${name}_l_stereo_camera_frame"/>
    </joint>
    <link name="${name}_l_stereo_camera_frame">
      
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0.000"  ixz="0.000"
                 iyy="0.001" iyz="0.000"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_l_stereo_camera_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_l_stereo_camera_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
        
        <material name="Blue" />
      </visual>

      <collision name="${name}_l_stereo_camera_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_l_stereo_camera_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
      
    </link>

    <joint name="${name}_r_stereo_camera_frame_joint" type="fixed">
      <origin xyz="${stereo_dx} ${stereo_dy} ${stereo_dz}" rpy="${stereo_rx} ${stereo_ry} ${stereo_rz}" />
      <parent link="${name}_l_stereo_camera_frame"/>
      <child link="${name}_r_stereo_camera_frame"/>
    </joint>
    <link name="${name}_r_stereo_camera_frame">
      
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0.000"  ixz="0.000"
                 iyy="0.001" iyz="0.000"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_r_stereo_camera_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_r_stereo_camera_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
        
        <material name="Blue" />
      </visual>

      <collision name="${name}_r_stereo_camera_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_r_stereo_camera_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
      
    </link>

  </macro>

</robot>
